### ISSUE TITLE
TODOs for revision

### ISSUE THREAD

**Issue by smoh** [smoh/gaia-comoving-stars#27]
- [x] cite http://adsabs.harvard.edu/abs/2011ApJS..192....2S
- [x] emphasize no cut-off for wide binaries separation
- [x] add sentence to caption of false-positive rate plot to say that we are over-estimating because of projections

**Comment by adrn** [comment]
How's this going?

**Comment by smoh** [comment]
Sending out today, just checking the appendix and one final read. I know I
suck..


On April 4, 2017 at 3:58:04 PM, Adrian Price-Whelan (
notifications@github.com) wrote:

How's this going?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/smoh/gaia-comoving-stars/issues/27#issuecomment-291614284>,
or mute the thread

**Comment by adrn** [comment]
No, you're rocking it! 🎸

**Comment by adrn** [comment]
💃
